apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-reader-fe
  labels:
    app: news-reader-fe
spec:
  replicas: 2
  selector:
    matchLabels:
      app: news-reader-fe
  template:
    metadata:
      labels:
        app: news-reader-fe
    spec:
      containers:
      - name: news-reader-fe
        image: news-reader-fe:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: news-reader-service
spec:
  type: ClusterIP
  selector:
    app: news-reader-fe
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80