apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: news-reader-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: news.danyeon.cloud
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: news-reader-service
            port:
              number: 80